# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Eating' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '= 4.5.1'
  pod 'Localize-Swift', '= 2.0'
  # Pods for Eating

  target 'EatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EatingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
